version: '3'

services:
  traefik:
    image: traefik:latest
    ports:
      - "80:80"
      - '443:443'
      - "8080:8080"
    volumes:
      - /etc/traefik/traefik.toml:/etc/traefik/traefik.toml
      - /etc/traefik/acme.json:/acme.json
      - /var/run/docker.sock:/var/run/docker.sock