version: '3'

services:
  traefik:
    image: traefik:latest
    command: -c /dev/null --api --docker --docker.domain=docker.localhost --logLevel=DEBUG
    ports:
      - "80:80"
      - '443:443'
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock